### ISSUE TITLE
It opens system browser on android

### ISSUE THREAD

**Issue by visortown** [TobyEb/cordova-plugin-colored-browser-tabs#1] opened 2019-04-04 04:49 UTC
iOS works fine, but on android it opens system browser instead. Any suggestions?

ionic (Ionic CLI) : 3.20.1
cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
@ionic/app-scripts : 3.2.2
Cordova Platforms  : android 7.1.4 ios 4.5.5
Ionic Framework    : ionic-angular 3.9.2

**Comment by TobyEb** [comment] 2019-04-04 05:59
Hi,

Thanks for giving my plugin a try. Unfortunately it won't work on Android when no chromium based browser is installed and set as default. 

For more Infos about chrome custom tabs you can check here. https://developer.chrome.com/multidevice/android/customtabs

Please check if a chromium based browser is set, when it still doesn't work, feel free to contact me again.

**Comment by visortown** [comment] 2019-04-04 06:27
Thank you for the quick reply! Not sure if I understand it correctly, but I do have "com.android.support:customtabs:23.3.0" in the dependencies. I was able to get cordova-plugin-browsertab to work but not anymore after I updated Cordova-android.

**Comment by TobyEb** [comment] 2019-04-04 06:52
ok, normally you don't have to add the gradle dependency again, this should already be handled by the plugin.

can you give some more information? 
- on what device are you testing
- what browser is your default browser? (Settings > Apps > Default Apps -> Browser App)

i think the problem is that you don't have any chromium based browser app installed on your device, e.g. Chrome or Brave.

**Comment by visortown** [comment] 2019-04-04 08:42
Thank you again for the information! I am testing on Redmi 5 (android 8.1.0) with Chrome installed. The default browser is not chrome and it does not seem to allow me to change it. However, as I said, previously the browsertab plugin was working on the same device with the same chrome app installed.

**Comment by TobyEb** [comment] 2019-04-04 09:57
ok thanks, i will test it with your given versions and give you as soon as possible feedback

**Comment by TobyEb** [comment] 2019-04-04 13:08
i now tested with your versions given. i cant reproduce this issue. but when i set my default browser to Xiaomis Mint browser, the custom tabs don't work, when i switch back to chrome everything works as expected, so i think the problem is the configuration of your device. the custom tabs just work when your default browser supports it. i think the most common browsers support it, but unfortunately not
xiaomis browser...

can you test it on another device? and give me a quick answer if it works there?

**Comment by visortown** [comment] 2019-04-04 16:33
Thank you for checking. It's still not working on Galaxy virtual devices. 
Also, the tab color is not true to itself. The following picture shows what the tab is colored, and what the app is colored with the same code '#0070A0' (themeablebrowser shows the color correctly).
[https://www.dropbox.com/s/nxw75xqv0hhx8o7/compare.png?dl=0](url)

**Comment by TobyEb** [comment] 2019-04-05 07:32
hi, yeah sorry for the color dismatch, its caused because the SafariViewControllers Toolbar is Translucent, right now there is unfortunately no way to turn this off (at least i found no one). 

Can you please test your problem on android with an Android Studio Simulator?

**Comment by visortown** [comment] 2019-04-06 07:18
I have been using Android Studio Simulator and it always prompts to open the Chrome App.

**Comment by TobyEb** [comment] 2019-04-06 08:12
Please accept the prompt, custom tab will open afterwards...

**Comment by visortown** [comment] 2019-04-06 12:35
I want it to open within the app as it does on iOS. don’t want the user to leave the app.

**Comment by TobyEb** [comment] 2019-04-06 15:03
You have to accept the prompt otherwise the app can't open chrome custom tabs, as the name suggests without chrome or any other supporting browser it won't work. After accepting it the in app browser will open. I will close the issue soon if you can't give me an appropriate error report, because without one I can't really help you...

**Closed as completed** 2019-04-06 17:48 UTC
